export const adminPaths = {
  session: "/v1/admin/session",
  listings: "/v1/admin/listings",
  listing: (publicId: string) => `/v1/admin/listings/${encodeURIComponent(publicId)}`,
  listingAudit: (publicId: string) => `/v1/admin/listings/${encodeURIComponent(publicId)}/audit`,
  listingTransition: (publicId: string) => `/v1/admin/listings/${encodeURIComponent(publicId)}/transition`,
  listingRestore: (publicId: string) => `/v1/admin/listings/${encodeURIComponent(publicId)}/restore`,
  listingBulk: "/v1/admin/listings/bulk-actions",
  listingRemoveAll: "/v1/admin/listings/remove-all",
  users: "/v1/admin/users",
  user: (publicId: string) => `/v1/admin/users/${encodeURIComponent(publicId)}`,
  userStatus: (publicId: string) => `/v1/admin/users/${encodeURIComponent(publicId)}/status`,
  dealers: "/v1/admin/vendors",
  dealer: (publicId: string) => `/v1/admin/vendors/${encodeURIComponent(publicId)}`,
  dealerStatus: (publicId: string) => `/v1/admin/vendors/${encodeURIComponent(publicId)}/status`,
  dealerVerifications: (publicId: string) => `/v1/admin/vendors/${encodeURIComponent(publicId)}/verifications`,
  dealerBilling: (publicId: string) => `/v1/admin/vendors/${encodeURIComponent(publicId)}/billing`,
  dealerSuspend: (publicId: string) => `/v1/admin/vendors/${encodeURIComponent(publicId)}/suspend`,
  dealerReinstate: (publicId: string) => `/v1/admin/vendors/${encodeURIComponent(publicId)}/reinstate`,
  verificationReview: (publicId: string) => `/v1/admin/verifications/${encodeURIComponent(publicId)}/review`,
  upload: (purpose: "LISTING_IMAGE" | "VENDOR_LOGO" | "VENDOR_BANNER" | "VEHICLE_MAKE_LOGO" | "BANNER_IMAGE") => `/v1/admin/files/upload?purpose=${purpose}`,
  makes: "/v1/admin/taxonomy/makes",
  make: (publicId: string) => `/v1/admin/taxonomy/makes/${encodeURIComponent(publicId)}`,
  models: (makePublicId: string) => `/v1/admin/taxonomy/makes/${encodeURIComponent(makePublicId)}/models`,
  model: (publicId: string) => `/v1/admin/taxonomy/models/${encodeURIComponent(publicId)}`,
  generations: (modelPublicId: string) => `/v1/admin/taxonomy/models/${encodeURIComponent(modelPublicId)}/generations`,
  generation: (publicId: string) => `/v1/admin/taxonomy/generations/${encodeURIComponent(publicId)}`,
  trims: (generationPublicId: string) => `/v1/admin/taxonomy/generations/${encodeURIComponent(generationPublicId)}/trims`,
  trim: (publicId: string) => `/v1/admin/taxonomy/trims/${encodeURIComponent(publicId)}`,
  countries: "/v1/admin/locations/countries",
  cities: "/v1/admin/locations/cities",
  areas: "/v1/admin/locations/areas",
  settings: "/v1/admin/settings",
  notifications: "/v1/admin/notifications",
  notificationBroadcast: "/v1/admin/notifications/broadcast",
  reports: "/v1/admin/reports",
  report: (publicId: string) => `/v1/admin/reports/${encodeURIComponent(publicId)}`,
  marketplaceLeads: "/v1/admin/marketplace/leads",
  marketplaceLeadStatus: (publicId: string) => `/v1/admin/marketplace/leads/${encodeURIComponent(publicId)}/status`,
  marketplaceOffers: "/v1/admin/marketplace/offers",
  marketplaceOfferStatus: (publicId: string) => `/v1/admin/marketplace/offers/${encodeURIComponent(publicId)}/status`,
  marketplaceConversations: "/v1/admin/marketplace/conversations",
  marketplaceConversationMessages: (publicId: string) => `/v1/admin/marketplace/conversations/${encodeURIComponent(publicId)}/messages`,
  marketplaceConversationStatus: (publicId: string) => `/v1/admin/marketplace/conversations/${encodeURIComponent(publicId)}/status`,
  jobs: "/v1/admin/listing-imports/jobs",
  job: (publicId: string) => `/v1/admin/listing-imports/jobs/${encodeURIComponent(publicId)}`,
  billingInvoices: "/v1/admin/vendor-billing/invoices",
  billingPayments: "/v1/admin/vendor-billing/payments",
  billingPaymentReview: (publicId: string) => `/v1/admin/vendor-billing/payments/${encodeURIComponent(publicId)}/review`,
  invoiceSettleOffline: (publicId: string) => `/v1/admin/vendor-billing/invoices/${encodeURIComponent(publicId)}/settle-offline`,
  subscriptionPlans: "/v1/admin/subscription-plans",
  subscriptionPlan: (publicId: string) => `/v1/admin/subscription-plans/${encodeURIComponent(publicId)}`,
  banners: "/v1/admin/banners",
  banner: (publicId: string) => `/v1/admin/banners/${encodeURIComponent(publicId)}`,
  promotions: "/v1/admin/promotions",
  promotionBoost: "/v1/admin/promotions/boost",
  vendorCreditAdjust: (vendorId: string) => `/v1/admin/vendors/${encodeURIComponent(vendorId)}/credits/adjust`,
  verifications: "/v1/admin/verifications",
  verification: (publicId: string) => `/v1/admin/verifications/${encodeURIComponent(publicId)}`,
  duplicates: "/v1/admin/duplicates",
  duplicatesScan: "/v1/admin/duplicates/scan",
  duplicateResolve: (publicId: string) => `/v1/admin/duplicates/${encodeURIComponent(publicId)}/resolve`,
  staff: "/v1/admin/users?type=admin",
  adminUserCreate: "/v1/admin/users",
  roles: "/v1/admin/roles",
  roleAssign: "/v1/admin/roles/assign",
  roleRevoke: (userId: string | number, roleId: number) => `/v1/admin/roles/users/${userId}/roles/${roleId}`,
  egyptSync: "/v1/admin/locations/egypt/sync",
  country: (id: string | number) => `/v1/admin/locations/countries/${id}`,
  city: (id: string | number) => `/v1/admin/locations/cities/${id}`,
  area: (id: string | number) => `/v1/admin/locations/areas/${id}`,
  opsQueues: "/v1/admin/ops/queues",
  opsWebhooks: "/v1/admin/ops/webhooks",
  opsHealth: "/v1/admin/ops/health",
  maintenance: "/v1/admin/settings/maintenance",
  smsTest: "/v1/admin/sms/test",
  mediaPurge: "/v1/admin/media/purge",
} as const;
